### ISSUE TITLE
Moving a repo to this GitHub organisation account 

### ISSUE THREAD

**Issue by BatoolMM** [ResearchCodeReviewCommunity/ResearchCodeReviewCommunity.github.io#1]
I'm not sure if this is the correct place to open this issue but I'd like to move this [repo](https://github.com/BatoolMM/Code-review-Training-and-Education) to this GitHub organisation account, if possible, please?

The repository was created for the Training and Education Working group!

**Comment by fcooper8472** [comment]
Hi @BatoolMM,

I have added you to the organisation: you should have a notification/email about that.  Let me know if it works OK.

**Comment by BatoolMM** [comment]
Thank you, Fergus!
